---
- hosts: master:worker
  become: yes
  tasks: 
    - name: Update the System
      apt:
        upgrade: yes
        cache_update: yes
    - name: Install dependencies
      apt:
        name: {{item}}
        state: present
      loop:
        - apt-transport-https
        - curl
    - name: Install Containered
      apt:
        pkg:
          - containerd
        state: present
    - name: Create /etc/containerd directory
      file:
        path: /etc/containerd
        state: directory
        mode: '0755'
    - name: Generate default containerd config
      command: containerd config default
      register: containerd_config
    - name: Write containerd config to /etc/containerd/config.toml
      copy:
        content: "{{ containerd_config.stdout }}"
        dest: /etc/containerd/config.toml
        mode: '0644'
    - name: Update SystemdCgroup to true in containerd config
      replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'
        backup: yes
    - name: Restart containerd service
      systemd:
        name: containerd
        state: restarted
        enable: yes
    - name: Ensure /etc/apt/keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Kubernetes GPG key and save it
      ansible.builtin.command: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
      register: kubernetes_key

    - name: Save the Kubernetes GPG key
      copy:
        content: "{{ kubernetes_key.stdout }}"
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        mode: '0644'

    - name: Add Kubernetes APT repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
        state: present
        filename: 'kubernetes'

    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install Kubernetes packages
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        force: yes

    - name: Hold Kubernetes packages
      ansible.builtin.command: sudo apt-mark hold kubelet kubeadm kubectl

    - name: Disable swap
      command: swapoff -a

    - name: Comment out swap entries in /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '^(\S+\s+\S+\s+swap\s+\S+\s+\S+\s+\S+)$'
        replace: '#\1'
        backup: yes

    - name: Load overlay module
      modprobe:
        name: overlay
        state: present

    - name: Load br_netfilter module
      modprobe:
        name: br_netfilter
        state: present
    
    - name: Create /etc/sysctl.d/k8s.conf with required settings
      copy:
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
        dest: /etc/sysctl.d/k8s.conf
        mode: '0644'

    - name: Apply sysctl settings
      command: sysctl --system